### ISSUE TITLE
Study preview mode

### ISSUE THREAD

**Issue by smeddinck** [MORE-Platform/more-studymanager-backend#224]
make it possible to preview a study without affecting the planned study start … data will be deleted when study is properly started … alternatively e.g. after X days ... tokens will be renewed upon starting study if already used during preview ... allow for maximum editing abilities during preview ... 

Has a frontend component (button to start + popup dialogue with information and warnings) as well ...

**Comment by andresgruber** [comment]
@smeddinck : This needs further refinement!

**Comment by smeddinck** [comment]
Ideally can define time point at which the preview begins (can start at a virtual timepoint in study period) ...

**Comment by ja-fra** [comment]
@smeddinck - this would be our suggested change to the study-workflow in More:

```mermaid
---
title: MORE Study Workflow (with Preview Mode)
---
flowchart TD
classDef default stroke-width:2px,fill:none,color:#6e8fac,stroke:#6e8fac
classDef endNode stroke-width:4px
classDef newNode fill:#ebcca2

linkStyle default stroke:#6e8fac,text:none

    start((( )))
    draft(Draft)
    active(Active)
    paused(Paused)
    completed(Completed):::endNode

    preview(Preview):::newNode
    preview-paused(Paused Preview):::newNode

    start -->|create| draft
    draft --->|start| active
    active --->|complete| completed
    active -->|pause| paused
    paused -->|resume| active

    draft -->|start preview| preview
    preview -->|complete preview| draft
    preview -->|pause preview| preview-paused
    preview-paused -->|resume preview| preview
```

We would reset the study/cleanup the data on the `complete preview` transition.

**Comment by smeddinck** [comment]
yes, this seems fully in-line with how we thought about this and discussed; thank you for spelling it out so clearly

**Comment by smeddinck** [comment]
accidentally closed but prior comment was just to confirm the approach

**Comment by alireza-dhp** [comment]
When a study is paused in preview mode, adding or editing records on participant, observation, integration and intervention tabs are not possible!

![Image](https://github.com/MORE-Platform/more-studymanager-backend/assets/107924035/6d8d8839-f8aa-4ae8-b922-4194f57ae428)
