### ISSUE TITLE
Improve Status Codes and Messages for External Integration Responses

### ISSUE THREAD

**Issue by alireza-dhp** [MORE-Platform/more-studymanager-backend#350]
When an integration is triggered via its endpoint API, the returned status codes are unclear and lack sufficient messaging for clarity. It should return more descriptive messages to improve understanding. 
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes 

For instance, when a study is paused, it returns a 204 (No Content) status code, but the data isn't saved. 
Similarly, when the sent timestamp is incorrect (outside the observation interval), it returns a 401 (Unauthorized) status code.

**Comment by janoliver20** [comment]
https://github.com/MORE-Platform/more-data-gateway/pull/190

**Comment by janoliver20** [comment]
https://github.com/MORE-Platform/more-data-gateway/pull/194

**Comment by janoliver20** [comment]
We have solved this issue by applying multiple different status codes for the endpoint `/external/bulk`:
- **202 Accepted**: `"Data successfully processed!"`
- **403 Forbidden**: `"Invalid token!"`
- **409 Conflict**: `"Study or participant is not active"`
- **422 Unprocessable Entity**:
    - `"Malformed participant id!"`
    - `"Data points are outside the acceptable timeframe."`

- **404 Not Found**: `"TimeFrame not found."`
- **400 Bad Request**: `"An unexpected error occurred."`
