### ISSUE TITLE
Observation Schedule Change Not Reflected in Integration

### ISSUE THREAD

**Issue by alireza-dhp** [MORE-Platform/more-studymanager-backend#351]
Bug: Integration module fails to update when the corresponding observation schedule is changed.

Steps to reproduce:

1. Create a study with an external observation.
2. Set an absolute schedule for the observation (e.g., from 01.10.2024 10:00 to 01.12.2024 22:00).
3. Link the observation to an external integration.
4. Start the study.

Data is sent periodically using the generated token from the integration.

Issue:
When the study is paused and the observation schedule is updated to **05**.10.2024 10:00 - 01.12.2024 22:00, data continues to persist for the outdated timestamp range (01.10.2024 10:00 to 05.10.2024 10:00).

Note:
The temporary workaround is deleting the observation and creating a new one, which requires generating a new integration with a new token, which is not a viable long-term solution. 
The integration should automatically handle schedule updates.

**Comment by janoliver20** [comment]
https://github.com/MORE-Platform/more-data-gateway/pull/190

**Comment by andresgruber** [comment]
Our latest changes ensure, that data is only collected with the current/latest observation schedule. This does NOT delete data, which may have been collected previously with another schedule.
