### ISSUE TITLE
Relative scheduler can exceed study duration without validation

### ISSUE THREAD

**Issue by rania-is** [MORE-Platform/more-studymanager-backend#352]
The relative scheduler currently allows users to configure a schedule that extends beyond the study duration, without any validation. For example, if the study duration is 14 days, the scheduler can still be configured to run from day 1 until day 20.

**Comment by janoliver20** [comment]
https://github.com/MORE-Platform/more-studymanager-frontend/pull/564

**Comment by janoliver20** [comment]
https://github.com/MORE-Platform/more-studymanager-frontend/pull/565

**Comment by janoliver20** [comment]
https://github.com/MORE-Platform/more-studymanager-frontend/pull/566

**Comment by andresgruber** [comment]
The new behavior implements the following rules while the study is configured: 
- The (optional) maximum study duration is limited by the planned study end (days = study-end minus study-start).
- The maximum duration of an observation is limited by the study duration. If no study duration is set, the limits are set by the planned study end.

Warnings appear in case one violates these rules. There is no rule  or warning to invalidate a study if one shortens the study duration afterwards. This rule affects the configuration of the study. For a participant of a study it is still possible to exceed the planned study - if one joins late.
